const countries = {
    "ar-SA" : "Arabic", 
    "en-US" : "English", 
    "en-GB" : "English (UK)",
    "ur-PK" : "Urdu",
    "pa-PK" : "Punjabi",
    "hi-IN" : "Hindi",
    "tr-TR" : "Turkish",
    "bn-IN" : "Bengali",
    "ps-PK" : "pashto",
    "gu-IN" : "Gujarati",
    "mr-IN" : "Marathi",
    "ta-IN" : "Tamil",
    "fr-FR" : "French", 
    "es-ES" : "Spanish", 
    "de-DE" : "German", 
    "ja-JP" : "Japanese",
    "ko-KR" : "Korean",
    "ru-RU" : "Russian",
    "fa-IR" : "Persian",
    "ku-TU" : "Kurdish",
}